version: '3.8'

services:
  app:
    build: .
    container_name: website
    volumes:
      - .:/usr/src/app
    ports:
      - "8888:8888"
    depends_on:
      - db_depa
    networks:
      - webnet
    environment:
      DB_HOST: 'db_depa'
      DB_USER: 'MYSQL_USER'
      DB_PASSWORD: 'MYSQL_PASSWORD'
      DB_DATABASE: 'EvaluationSheet'
      PORT: 8888

  db_depa:
    image: mysql:8
    container_name: db_depa
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password'  # Replace with your root password
      MYSQL_DATABASE: 'EvaluationSheet'
      MYSQL_USER: 'mysql_user'  # Replace with your desired MySQL user
      MYSQL_PASSWORD: 'mysql_password'  # Replace with your desired MySQL user password
    ports:
      - "3306:3306"
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-containers
    restart: always
    environment:
      PMA_HOST: db_depa
      PMA_PORT: "3306"
    ports:
      - "80:80"
    depends_on:
      - db_depa
    networks:
      - webnet

volumes:
  mysql-data:

networks:
  webnet:
